### ISSUE TITLE
Aufruf von huh.utils.choice.message

### ISSUE THREAD

**Issue by kehr-solutions** [heimrichhannot/contao-utils-bundle#1]
Beim Aufruf vom service 

> huh.utils.choice.message

 erhält man folgende Fehlermeldung

> Attempted to call an undefined method named "getCatalogue" of class "Contao\CoreBundle\Translation\Translator".

Wenn man in der klasse MessageChoice folgendes abändert

> $translator = \System::getContainer()->get('translator.default');

erscheint die Fehlermeldung nicht mehr.

**Comment by koertho** [comment]
Hi, can you please tell us the contao version you are using?

**Comment by koertho** [comment]
Das Problem dürfte am dekorierten Translator-Service von Contao 4.5 liegen, da werden nicht alle Interfaces des Original beachtet. Habe deine Änderung übernommen, sollte also in 2.28.4 behoben sein. Kannst du kurz Rückmeldung dazu geben?

**Comment by kehr-solutions** [comment]
Mit der Änderung funktioniert es wie gewünscht. Vielen Dank.
