### ISSUE TITLE
Disable utils bundle js

### ISSUE THREAD

**Issue by dmolineus** [heimrichhannot/contao-utils-bundle#13]
I have a multi domain setup where only one project uses your teaser bundle. However the utils bundle js is also available in other projects. As the projects don't manage any assets with Contao (assets are loaded by the assets component), the utils bundle js is the only one being injected everythere.

Is there any way to disable it, so that it is only loaded when required?

**Comment by koertho** [comment]
The JS-Code is added in the contao config file. You could unset the index in the `generatePage` hook (`$GLOBALS['TL_JAVASCRIPT']['contao-utils-bundle']`). Another way is currently not implemented, but it's a good point to make this configurable. We use our encore bundle and don't have to deal with such things ;)

**Comment by dmolineus** [comment]
Thanks for your replay. Killing the file with a custom hook listener is what I already do.

**Comment by koertho** [comment]
@dmolineus In Version 2.187 there is now an option to disable the assets. So you could replace your hook with the config. Sorry that it took so long!
