### ISSUE TITLE
PHP7.4

### ISSUE THREAD

**Issue by kehr-solutions** [heimrichhannot/contao-utils-bundle#18]
Hallo zusammen,

folgende Zeile https://github.com/heimrichhannot/contao-utils-bundle/blob/master/src/Dca/DcaUtil.php#L55 erfordert min. PHP7.4

Es müsste angepasst das es mit PHP7.1 funktioniert oder in der composer.json die PHP Version auf 7.4 setzen.
Vielen Dank.

**Comment by koertho** [comment]
@kehr-solutions Danke für die Info, ist behoben in 2.172.1
