### ISSUE TITLE
Vergessene debug Anweisung

### ISSUE THREAD

**Issue by Olli** [heimrichhannot/contao-utils-bundle#21]
Hier ist ein {{debug}} vergessen worden. Das führt auf nicht-dev Systemen zum Fehler.
https://github.com/heimrichhannot/contao-utils-bundle/blob/6b2d0848f375f4fbe3acba3bb45f8153048d41bc/src/Resources/views/image_gallery.html.twig#L1

**Comment by mirkogleibe** [comment]
Fixed with [https://github.com/heimrichhannot/contao-utils-bundle/releases/tag/2.180.1](url)
