### ISSUE TITLE
Compatibility with PHP < 7.4 broken

### ISSUE THREAD

**Issue by plorenz-etes** [heimrichhannot/contao-utils-bundle#49]
Since the FileUtil class has been added, this bundle only works in PHP 7.4+.
In line 16, typed properties are used ( https://github.com/heimrichhannot/contao-utils-bundle/blob/master/src/Util/File/FileUtil.php ):

```
private ContaoFramework $contaoFramework;
```

However, those are only supported since PHP 7.4. This broke a customer's Contao installation after an update because there's only 7.3 available on their webserver.
I suggest you either exclude older PHP versions from this release or you don't use typed properties :)

**Comment by koertho** [comment]
Thanks for reporting!
