### ISSUE TITLE
IE 11 Fehler im Javascript

### ISSUE THREAD

**Issue by arboc** [heimrichhannot/contao-utils-bundle#6]
Wenn man (in Contao 4.4) im Seitenlayout die Funktion "Skripte zusammenfassen" aktiviert, erhält man beim IE 11 einen Hinweis auf ein Syntaxfehler in der zusammengefassten Javascript-Datei. Dieser verweist auf den Teil aus der Datei: contao-utils-bundle.js

Ohne das Zusammenfassen läuft alles wie es soll.

**Comment by Defcon0** [comment]
Kannst du bitte einen Screenshot des Fehlers bereitstellen aus dem man ersieht, um welche Stelle im Code es genau geht? Ggf. zusammen mit der aggregierten Datei? Danke!

PS: Meines Wissens ist es in aktuellen Browsern dank HTTP/2 (Hoster-Support vorausgesetzt) nicht mehr nötig, Skripte zusammenzufassen. Genau genommen ist das sogar hinderlich, weil man so dem Protokoll die Möglichkeit entzieht, die Skripte in optimierter Reihenfolge zu laden.

**Comment by arboc** [comment]
Über Sinn und Unsinn dieser Funktion brauchen wir und nicht zu streiten...  
Die ist in Contao implementiert und wir hatten ein Theme, bei dem diese Funktion genutzt wurde. (Ist inzwischen deaktiviert)

Jetzt zum Screenshot:  
Der IE bemängelt einen Syntaxfehler an Pos. 976 (des minified scripts):
![image](https://user-images.githubusercontent.com/4447843/52469287-56e7ef80-2b8b-11e9-8acf-8758e1503d77.png)

**Comment by Defcon0** [comment]
OK, es gab auf jeden Fall ein Problem mit der Webpack-Generierung der Fallback-Variante des JavaScript-Codes. Dieser ist jetzt behoben.

Kannst du bitte die letzte Version (2.67.2) mal ausprobieren? Bei mir kommt der Fehler im IE 11 nicht mehr.

**Comment by arboc** [comment]
sieht gut aus, Danke 👍

**Comment by Defcon0** [comment]
Danke für den Hinweis. Das war ein grundlegenderes Problem. Gut, dass wir das ausbügeln konnten :-)
